# Generated by Django 3.2.1 on 2021-06-12 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_date_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name_plural': 'username'},
        ),
    ]
