# Generated by Django 3.2.1 on 2021-06-14 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_agre', '0002_auto_20210614_0956'),
        ('chat', '0004_auto_20210612_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirm_fill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client_filled', models.BooleanField(default=False)),
                ('Service_filled', models.BooleanField(default=False)),
                ('Room_nme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_or_Service', to='new_agre.rooms')),
            ],
            options={
                'verbose_name_plural': 'form filled',
            },
        ),
    ]
