# Generated by Django 3.2.1 on 2021-06-15 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_agre', '0002_auto_20210614_0956'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0006_auto_20210614_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Both_Signed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client_filled', models.BooleanField(default=False)),
                ('Service_filled', models.BooleanField(default=False)),
                ('Asigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asigned_sign', to=settings.AUTH_USER_MODEL)),
                ('Room_nme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_and_Service', to='new_agre.rooms')),
                ('Room_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_sign', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Both Signed',
            },
        ),
    ]
