# Generated by Django 3.2.1 on 2021-06-16 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_both_signed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='both_signed',
            old_name='Client_filled',
            new_name='Client_fill',
        ),
        migrations.RenameField(
            model_name='both_signed',
            old_name='Service_filled',
            new_name='Service_fill',
        ),
        migrations.RemoveField(
            model_name='both_signed',
            name='Asigned',
        ),
        migrations.RemoveField(
            model_name='both_signed',
            name='Room_owner',
        ),
    ]
