# Generated by Django 3.2.1 on 2021-08-06 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_agre', '0023_agree_edits_ex_signed_pdf'),
        ('chat', '0008_auto_20210616_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Both_edited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client_fill', models.BooleanField(default=False)),
                ('Service_fill', models.BooleanField(default=False)),
                ('Room_nme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_check_edits', to='new_agre.rooms')),
            ],
            options={
                'verbose_name_plural': 'Both edited',
            },
        ),
    ]
