# Generated by Django 3.2.1 on 2021-06-12 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_name', models.CharField(max_length=20)),
                ('Room_password1', models.CharField(max_length=15)),
                ('Room_password2', models.CharField(max_length=15, null=True)),
                ('Asigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests_asigned', to=settings.AUTH_USER_MODEL)),
                ('Room_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Registerd Rooms',
            },
        ),
        migrations.CreateModel(
            name='Contract_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client_Company_name', models.CharField(blank=True, max_length=20, null=True)),
                ('Client_main_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('Client_office_hours', models.CharField(blank=True, max_length=20, null=True)),
                ('Purpose_of_sla', models.CharField(blank=True, max_length=200, null=True)),
                ('Goal_of_sla', models.CharField(blank=True, max_length=200, null=True)),
                ('Sla_objectives1', models.CharField(blank=True, max_length=200, null=True)),
                ('Sla_objectives2', models.CharField(blank=True, max_length=200, null=True)),
                ('Sla_objectives3', models.CharField(blank=True, max_length=200, null=True)),
                ('Sla_objectives4', models.CharField(blank=True, max_length=200, null=True)),
                ('Sla_start_date', models.DateTimeField()),
                ('Sla_end_date', models.DateTimeField()),
                ('Client_performance_review', models.CharField(blank=True, max_length=200, null=True)),
                ('Service_performance_review', models.CharField(blank=True, max_length=20, null=True)),
                ('Perfomace_review_frequency', models.CharField(blank=True, max_length=200, null=True)),
                ('Next_Review_date', models.DateTimeField()),
                ('Service_to_supply', models.CharField(blank=True, max_length=200, null=True)),
                ('Service_Detailed_description1', models.CharField(blank=True, max_length=200, null=True)),
                ('Service_Detailed_description2', models.CharField(blank=True, max_length=200, null=True)),
                ('Service_Detailed_description3', models.CharField(blank=True, max_length=200, null=True)),
                ('Service_Detailed_description4', models.CharField(blank=True, max_length=200, null=True)),
                ('Service_provider_requirement1', models.CharField(blank=True, max_length=200, null=True)),
                ('Service_provider_requirement2', models.CharField(blank=True, max_length=200, null=True)),
                ('Service_provider_requirement3', models.CharField(blank=True, max_length=200, null=True)),
                ('Service_provider_requirement4', models.CharField(blank=True, max_length=200, null=True)),
                ('Customer_Requirement1', models.CharField(blank=True, max_length=200, null=True)),
                ('Customer_Requirement2', models.CharField(blank=True, max_length=200, null=True)),
                ('Customer_Requirement3', models.CharField(blank=True, max_length=200, null=True)),
                ('Client_tel_no', models.CharField(blank=True, max_length=20, null=True)),
                ('Client_service_office_no', models.CharField(blank=True, max_length=20, null=True)),
                ('Company_SP_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests_created', to='base.company_details')),
                ('Room_nme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests_created', to='new_agre.rooms')),
            ],
            options={
                'verbose_name_plural': 'Contract_Form',
            },
        ),
    ]
