# Generated by Django 3.2.1 on 2021-06-19 18:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('new_agre', '0002_auto_20210614_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreemnets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Signed_pdf', models.FileField(blank=True, null=True, upload_to='new_agre/templates/pdfs')),
                ('Private_key', models.CharField(max_length=40)),
                ('Public_key', models.CharField(max_length=40)),
                ('Dig_sig', models.CharField(max_length=40)),
                ('Service_prov', models.CharField(max_length=20)),
                ('Client', models.CharField(max_length=20)),
                ('hash_no', models.CharField(max_length=40)),
                ('date_signed', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('Room_nme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Agree', to='new_agre.rooms')),
            ],
            options={
                'verbose_name_plural': 'Agreemnets',
            },
        ),
    ]
