# Generated by Django 3.2.1 on 2021-06-19 20:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('new_agre', '0003_agreemnets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreemnets',
            name='Client',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='agreemnets',
            name='Dig_sig',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='agreemnets',
            name='Private_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='agreemnets',
            name='Public_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='agreemnets',
            name='Service_prov',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='agreemnets',
            name='date_signed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='agreemnets',
            name='hash_no',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
