# Generated by Django 3.2.1 on 2021-06-20 00:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('new_agre', '0005_auto_20210619_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agree_edits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Signed_pdf', models.FileField(blank=True, null=True, upload_to='new_agre/templates/pdfs')),
                ('date_signed', models.DateTimeField(default=django.utils.timezone.now)),
                ('Room_nme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Agree1', to='new_agre.rooms')),
            ],
            options={
                'verbose_name_plural': 'Agree_edits',
            },
        ),
    ]
