# Generated by Django 3.2.1 on 2021-06-20 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_agre', '0006_agree_edits'),
    ]

    operations = [
        migrations.AddField(
            model_name='agree_edits',
            name='Agreement_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
