# Generated by Django 3.2.1 on 2021-06-20 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_agre', '0008_alter_agree_edits_signed_pdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agree_edits',
            old_name='Signed_pdf',
            new_name='final_pdf',
        ),
    ]
