# Generated by Django 3.2.1 on 2021-06-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_agre', '0009_rename_signed_pdf_agree_edits_final_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agree_edits',
            name='final_pdf',
        ),
        migrations.AddField(
            model_name='agree_edits',
            name='hash_no',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
