# Generated by Django 3.2.1 on 2021-06-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_agre', '0011_auto_20210621_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='agree_edits',
            name='Dig_sig',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
