# Generated by Django 3.2.1 on 2021-07-04 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_agre', '0012_agree_edits_dig_sig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreemnets',
            name='Signed_pdf',
            field=models.FileField(blank=True, null=True, upload_to='base/static/base/media'),
        ),
    ]
