# Generated by Django 3.2.1 on 2021-07-18 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_agre', '0016_alter_agreemnets_signed_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreemnets',
            name='Done',
            field=models.BooleanField(default=False),
        ),
    ]
