# Generated by Django 3.2.1 on 2021-08-04 16:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('new_agre', '0017_agreemnets_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreemnets',
            name='Client',
        ),
        migrations.RemoveField(
            model_name='agreemnets',
            name='Service_prov',
        ),
        migrations.AddField(
            model_name='agreemnets',
            name='date_Client_sign',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='agreemnets',
            name='date_Service_prov_sign',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
