# Generated by Django 3.2.1 on 2021-08-04 17:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('new_agre', '0019_auto_20210804_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreemnets',
            name='date_Client_sign',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='agreemnets',
            name='date_Service_prov_sign',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
