# Generated by Django 3.2.1 on 2021-08-04 18:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('new_agre', '0021_remove_agreemnets_date_signed'),
    ]

    operations = [
        migrations.AddField(
            model_name='agree_edits',
            name='date_edited',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
