# Generated by Django 3.2.1 on 2021-08-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_agre', '0022_agree_edits_date_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='agree_edits',
            name='Ex_Signed_pdf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
