# Generated by Django 3.2.1 on 2021-08-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_agre', '0023_agree_edits_ex_signed_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreemnets',
            name='Real_Done',
            field=models.BooleanField(default=False),
        ),
    ]
