# Generated by Django 3.2.1 on 2021-06-12 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_id', models.CharField(max_length=5)),
                ('Company_password', models.CharField(max_length=13)),
                ('Company_address', models.CharField(max_length=80)),
                ('Company_name', models.CharField(max_length=20)),
                ('Company_email', models.EmailField(max_length=254)),
                ('Company_reg_no', models.CharField(max_length=10)),
                ('Company_director', models.CharField(max_length=40)),
                ('Company_motto', models.CharField(max_length=40)),
                ('Company_phn_no', models.CharField(max_length=15)),
                ('services_summary', models.CharField(max_length=40)),
                ('login_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Companies database',
            },
        ),
        migrations.CreateModel(
            name='Client_OR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_client', models.BooleanField(default=True)),
                ('login_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Client OR',
            },
        ),
        migrations.CreateModel(
            name='Client_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client_address', models.CharField(max_length=80)),
                ('Client_lname', models.CharField(max_length=20)),
                ('Client_fname', models.CharField(max_length=20)),
                ('Client_phn_no', models.CharField(max_length=15)),
                ('login_own', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Client database',
            },
        ),
    ]
