# Generated by Django 3.2.1 on 2021-06-17 16:45

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_pdf', models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='/base/'), upload_to='')),
            ],
            options={
                'verbose_name_plural': 'pdfs',
            },
        ),
    ]
