# Generated by Django 3.2.1 on 2021-06-17 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_pdf'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pdf',
            new_name='pdf1',
        ),
    ]
