# Generated by Django 3.2.1 on 2021-06-19 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210617_1918'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
