# Generated by Django 3.2.1 on 2021-06-21 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_delete_yourmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_details',
            name='Company_password',
        ),
    ]
