# Generated by Django 3.2.1 on 2021-06-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_company_details_company_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_details',
            name='Company_website',
            field=models.CharField(blank=True, default='dygdeygeyg', max_length=30, null=True),
        ),
    ]
