# Generated by Django 3.2.1 on 2021-06-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_company_details_company_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_details',
            name='services_summary',
            field=models.CharField(max_length=900),
        ),
    ]
