# Generated by Django 3.2.1 on 2021-08-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_company_details_services_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_details',
            name='Company_website',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
